#!/usr/bin/env python

#########
# Import #
#########

import argparse
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio import Seq

#########
# args #
#########

def get_args():
    parser = argparse.ArgumentParser(description="A program to convert multi-line fasta into one line fasta")
    parser.add_argument("-f", "--file", help="designates absolute file path to fasta file", required=True)
    parser.add_argument("-o", "--outfile", help="designates absolute file path to the output file", required=False)    
    return parser.parse_args()
args=get_args()

# ./oneline_fasta.py -f plasmid_seq.fasta -o oneline_plasmid.csv

record_list = []
label = 'bacteria'
with open(args.file, 'r') as fasta_in, open(args.outfile, 'w') as csv_out:
	for record in SeqIO.parse(fasta_in, 'fasta'):	
		if record.id in record_list:
			pass
		else:
			record_list.append(record.id)
			csv_out.write(f">{record.id}, {label}, {str(record.seq)}" + "\n")
